// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: logs.sql

package db

import (
	"context"
	"database/sql"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs(
    project_id,
    event_id,
    account_id,
    data
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, project_id, event_id, account_id, data, created_at
`

type CreateLogParams struct {
	ProjectID int64          `json:"projectID"`
	EventID   int64          `json:"eventID"`
	AccountID string         `json:"accountID"`
	Data      sql.NullString `json:"data"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.ProjectID,
		arg.EventID,
		arg.AccountID,
		arg.Data,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.AccountID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM logs WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLog, id)
	return err
}

const getLog = `-- name: GetLog :one
SELECT id, project_id, event_id, account_id, data, created_at FROM logs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLog(ctx context.Context, id int64) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLog, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.AccountID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, project_id, event_id, account_id, data, created_at FROM logs
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.AccountID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
