// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAdmin(ctx context.Context, username string) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteProjectLogs(ctx context.Context, projectID int64) error
	DeleteUser(ctx context.Context, id string) error
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetEventByName(ctx context.Context, name string) (Event, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByProjectAccountId(ctx context.Context, projectAccountID sql.NullString) (User, error)
	GetUserByUUID(ctx context.Context, uuid sql.NullString) (User, error)
	ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error)
	ListEventsByProjectId(ctx context.Context, projectID int64) ([]Event, error)
	ListProjectLog(ctx context.Context, arg ListProjectLogParams) ([]Log, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListUserLog(ctx context.Context, arg ListUserLogParams) ([]Log, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
