// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteAccount(ctx context.Context, accountID string) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteLog(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, accountID string) (Account, error)
	GetAccountForUpdate(ctx context.Context, accountID string) (Account, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetLog(ctx context.Context, id int64) (Log, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
